spring.application.name=java-ingestion-service
server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
refinery.output.base-directory=../../data/processed